package:
    name: ibex-lib
    version: 2.4.2


source:
    url: https://github.com/benEnsta/ibex-lib/archive/with_cmake.zip
#    git_url: https://github.com/benEnsta/ibex-lib.git
#s    version: {{ environ['GIT_DESCRIBE_TAG'] }}

build:
  # script_env:
  #   - CC
  #   - CXX
  number: 0

requirements:
    build:
        - cmake

about:
    home: http://ibex-lib.org
