package:
    name: ibex-lib
    version: 2.3.0

source:
    url: https://github.com/benEnsta/ibex-lib/archive/with_cmake.zip
#    git_url: https://github.com/benEnsta/ibex-lib.git
#s    version: {{ environ['GIT_DESCRIBE_TAG'] }}

build:
    number: 0

requirements:
    build:
        - cmake

about:
    home: http://ibex-lib.org
