# The language in this case has no bearing - we are going to be making use of conda.
language: objective-c

sudo: false

env:
  global:
    # add ANACONDA_TOKEN
    secure: kLlW/eFYXyFuxKew0fcE22A2+iaFtBI29wYDCPcAc+xHz8zB2XptVzEP2atH5913nUwKOBCKy7LJM5xcYOi1512HSqUG+DOWZXeQf8fqlVMmrgGa3d5Ck+RirY/kt+jpUBIEH6johlnvphPi3v0iWshZahfXysD+dcikpbVCqc3RU7xHV5dCTGZSG/0UE0rZXh2pV5sfs0JRqpNvGWBQRUu0wv32C6m0PLXeqBK/PTQAB9qzLOKkMWPlx6gaTC8pYtGCq8UWhWC2wMXljgDRdLh9MnTzt9BWIPTYV0xZHkf+Qq8i+m84vM7/Oiq4ZtBuKa+oDf/Wz5uHa3cwiyyph5n2CRTKaAxFJ8NrP9/WEeyGrzlXTpYL8bXzS8T4FTdqnGFf9XGOTcfg85r8LM3bJ/U2MkolRiUgFJF1VnnsagxY9ioyhsGRRkxHN0hbkPJ5IRcCBK5vmo+Koi0/uJIBD4ZcjI/w0qhAYuph6wNlJuOo2sYVM6CdY0oI1dv9emGXD5r+AUyf1RLCq8WGklauRJMVAlxyfxn7VWg/18lD5A8cNYrf4XelDr0l0n0ii5VeurUHewcn93opkES1jvgBLgZ+Inmcm3rEBD/FygLA8vhHSkkOC2SACByFlcYagoEOeblx9O1PKN3WRZUSpDF9tqyf8KKOz/SqS5HXQTWLPLQ=

matrix:
  include:
    - os: osx
      env: ACTION="build-all"
    - os: linux
      env: ACTION="create-feedstocks-on-merge"

script:
  - if [ "$ACTION" = "create-feedstocks-on-merge" ]; then
      echo "Creating feedstocks from the recipe(s) (this simply lints the recipe if this isn't a merged commit to master).";
      source ./.CI/create_feedstocks;
    elif [ "$ACTION" = "build-all" ]; then
      echo "Building all recipes.";
      source ./.CI/build_all;
    fi

  - conda build --token ${ANACONDA_TOKEN} recipes/ibexlib --
