package:
  name: pyibex
  version: "1.5.0a4"

source:
  fn: pyibex-1.5.0a4.tar.gz
  url: https://testpypi.python.org/packages/74/60/6f83993f3c9802b8db8eaac7cb828503cac54aa0bf4412a17a0a929d9147/pyibex-1.5.0a4.tar.gz
  md5: f7c814cc9c9e00d11ac58b3f90677b34
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyibex = pyibex:main
    #
    # Would create an entry point called pyibex that calls pyibex.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pyibex
    - pyibex.examples
    - pyibex.geometry
    - pyibex.polar

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/benEnsta/pyIbex
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'PyIbex a python interface of ibexlib '

extra:
  recipe-maintainers:
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - BenEnsta
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
